<?php 
    //todo- move logic to helper???
    // $allowEdit = $this->CurrentUserIsCommentOwner($comment);
   
?>
<div class="comment-wrapper">
    <?php //hide edit form in comment wrapper, show it on click ?>
    <?php if($allowEdit):?>
        
            <?= $this->CommentEditForm($comment); ?>
  
    <?php endif; ?>
    <div>
        <span class="comment-discriptor-label"><?= $this->translate('Title') ?> : </span>
        <span class="module-comments-title"><strong><?= $this->EscapeHtml($comment->getTitle()) ?></strong> </span>
    </div>
    <div> 
        <span class="comment-discriptor-label"><?= $this->translate('Username') ?> : </span>
        <span class="module-comments-username"><strong><?= $this->EscapeHtml($comment->getUser()->getUserName()) ?></strong> </span>
        <?php
            //todo- write js to display, ajax, success, errors etc
            if($allowEdit):
        ?>
        <span class="comment-edit-button span-float-right">edit</span>
    <?php endif; ?>
    </div>
    <div>
        <span class="module-comments-comment"><?= $this->EscapeHtml($comment->getComment()) ?> </span>
    </div> 

    <div class="child-comments-wrapper" parent-id="<?= $comment->getId() ?>">
    <div class="child-comments" >
        <?php 
        //loop the child comments 
        foreach ($comment->getChildren() as $childComment) {
            echo $this->partial('comments/comment/child-comment.phtml', array('comment' => $childComment));
        }
        ?>
    </div><!-- end - class="child-comments"-->

    <span class="show-hide-child-comments-button comment-button"><?= $this->translate('Show Replies') ?></span>
    <span> || </span>
    <span class="reply-to-comment-button comment-button"><?= $this->translate('Reply') ?></span>
    <?php // todo- remove || ?>
    <?php if ($this->zfcUserIdentity() || 1) { ?>
    <?=  $this->renderChildModel('replyForm') ?>
       
    <?php } else { ?>
    //todo- think about how generic templ would login (widget???)
    <a href="<?php
                echo $this->url('scn-social-auth-user/login/provider', array('provider' => 'github'));
            ?>"><?= $this->translate('Login to reply') ?></a>
        
<?php } // end else  ?>
    <hr>
    </div><!-- end - class="child-comments-wrapper" -->
</div><!-- end - class="comment-wrapper" -->