<?php $allowEdit = $this->CurrentUserIsCommentOwner($comment); ?>

<div class="comment-wrapper">
    
    <div class="comment-labels">
    <div>
        <span class="comment-discriptor-label"><?= $this->translate('Title') ?> : </span>
        <span class="module-comments-title"><strong><?= $this->EscapeHtml($comment->getTitle()) ?></strong> </span>
    </div>
    <div> 
        <span class="comment-discriptor-label"><?= $this->translate('Username') ?> : </span>
        <span class="module-comments-username"><strong><?= $this->EscapeHtml($comment->getUser()->getUserName()) ?></strong> </span>
        </div>
        
        </div><!-- comment-labels -->
        <div>
        <?php
            //todo- change this
            if(!$allowEdit):
        ?>
        
            <span class="comment-edit-button comment-button">edit</span>
            <?php endif; ?>
                    <?php if(!$allowEdit || $this->CurrentUserIsModuleOwner($comment)) : ?>
            <span class="comment-close-button comment-button">close</span>
            <?php endif; ?>
        </div>
    
 
    <div class="comment-content">
        <span class="module-comments-comment"><?= $this->EscapeHtml($comment->getComment()) ?> </span>
    </div> 
    <?php //change this ?>
    <?php if(!$allowEdit):?>
        <div>
            <?= $this->CommentEditForm($comment); ?>
        </div>
    <?php endif; ?>
    <div class="child-comments-wrapper" parent-id="<?= $comment->getId() ?>">
    <div class="child-comments" >
        <?php 
        //loop the child comments 
        foreach ($comment->getChildren() as $childComment) {
            echo $this->partial('comments/comment/child-comment.phtml', array('comment' => $childComment));
        }
        ?>
    </div><!-- end - class="child-comments"-->

    <span class="show-hide-child-comments-button comment-button"><?= $this->translate('Show Replies') ?></span>
    <span> || </span>
   
    <?php if (!$this->zfcUserIdentity()) { ?>
    <span class="reply-to-comment-button comment-button"><?= $this->translate('Reply') ?></span>
    
    <?=  $this->render($replyForm) ?>
       
    <?php } else { 
    
    echo $this->loginLink($this);
        
    } // end else  ?>
    <hr>
    </div><!-- end - class="child-comments-wrapper" -->
</div><!-- end - class="comment-wrapper" -->