<?php

$form = $this->replyForm;

$parentId = $this->parentId;
$form->setAttribute('action', $this->url("comment/add-reply"));
$form->setAttribute('method', 'post');

$form->prepare();
?>
<form action="/comment/add-reply" method="post" class="reply-form reply" >
    
    <div class="element-wrapper">
        <input type="hidden" name="parent-id" value="<?php $parentId ?>" >
    </div><!-- end - class="input-wrapper"-->
   
    <div class="element-wrapper" required>
        <?= $this->formRow($form->get('content')); ?>
    </div><!-- end - class="input-wrapper"-->
    
    <div class="element-wrapper">
         <?= $this->formSubmit($form->get('submit')); ?>
    </div><!-- end - class="input-wrapper"-->

</form>