<?php
    $commentForm = $this->commentForm;
    $commentForm->prepare();
?>
<form action="/comment/edit-reply" method="post"  class="comment comment-form-edit">

    <div class="input-wrapper">
        <?= $this->formRow($commentForm->get('module-id')); ?>
    </div><!-- end - class="input-wrapper"-->
    <div class="input-wrapper">
        <?= $this->formRow($commentForm->get('id')); ?>
    </div><!-- end - class="input-wrapper"-->
   
     <div class="element-wrapper">
        <?= $this->formRow($commentForm->get('title')); ?>
    </div><!-- end - class="input-wrapper"-->
    <div class="element-wrapper">
        <?= $this->formRow($commentForm->get('comment')); ?>
    </div><!-- end - class="input-wrapper"-->
    
    <div class="element-wrapper">
         <?= $this->formSubmit($commentForm->get('submit')); ?>
    </div><!-- end - class="input-wrapper"-->

</form>